[project]
name = "stock-time-series-forecaster"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "kagglehub[hf-datasets,pandas-dataset]>=0.3.13",
]
